### ISSUE TITLE
Remove references to deprecated services.

### ISSUE THREAD

**Issue by floresam** [IBM-Bluemix-Docs/security#3]
Page https://console.bluemix.net/docs/security/index.html#security references services that are no longer available or have had name changes.

- [x] Application Security on Cloud (No longer available in IBM Cloud Platform catalog)

- [x] IBM Db2 on Cloud has been renamed to Db2 Hosted. Db2 on Cloud now refers to IBM's fully-managed Db2 cloud offering.

**Comment by plindblue** [comment]
Thanks, the updates have been made.
